// ===== 카페 앱 - 메뉴 / 카테고리 데이터 =====

export const CATEGORIES = [
  { id: "coffee", name: "커피" },
  { id: "non-coffee", name: "논커피" },
  { id: "tea", name: "티" },
  { id: "dessert", name: "디저트" },
];

export const TEMPERATURES = [
  { id: "HOT", name: "HOT" },
  { id: "ICE", name: "ICE" },
];

// 최초 1회 localStorage 시딩에 사용되는 기본 메뉴 데이터
export const INITIAL_MENUS = [
  {
    id: "menu-1",
    name: "아메리카노",
    category: "coffee",
    price: 4500,
    description: "진하게 내린 에스프레소에 물을 더해 깔끔하게 즐기는 기본 커피입니다.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/A_cup_of_Americano.JPG/960px-A_cup_of_Americano.JPG",
    temperatures: ["HOT", "ICE"],
    badge: "BEST",
    soldOut: false,
  },
  {
    id: "menu-2",
    name: "카페라떼",
    category: "coffee",
    price: 5000,
    description: "부드러운 스팀 밀크와 에스프레소가 조화를 이루는 커피입니다.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Caffe_Latte_cup.jpg/960px-Caffe_Latte_cup.jpg",
    temperatures: ["HOT", "ICE"],
    badge: "BEST",
    soldOut: false,
  },
  {
    id: "menu-3",
    name: "바닐라라떼",
    category: "coffee",
    price: 5500,
    description: "달콤한 바닐라 시럽이 더해져 부드럽고 향긋한 라떼입니다.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Hearts_in_latte_art%2C_Krak%C3%B3w%2C_Poland%2C_2023.jpg/960px-Hearts_in_latte_art%2C_Krak%C3%B3w%2C_Poland%2C_2023.jpg",
    temperatures: ["HOT", "ICE"],
    badge: null,
    soldOut: false,
  },
  {
    id: "menu-4",
    name: "카푸치노",
    category: "coffee",
    price: 5000,
    description: "풍성하고 부드러운 우유 거품이 매력적인 이탈리안 커피입니다.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Cappuccino_with_foam.jpg/960px-Cappuccino_with_foam.jpg",
    temperatures: ["HOT", "ICE"],
    badge: null,
    soldOut: false,
  },
  {
    id: "menu-5",
    name: "카라멜마키아토",
    category: "coffee",
    price: 5800,
    description: "달콤 쌉싸름한 카라멜과 에스프레소가 층층이 어우러진 커피입니다.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/2023-09-27_Latte_Macchiato.jpg/960px-2023-09-27_Latte_Macchiato.jpg",
    temperatures: ["HOT", "ICE"],
    badge: null,
    soldOut: false,
  },
  {
    id: "menu-6",
    name: "콜드브루",
    category: "coffee",
    price: 5200,
    description: "찬물로 긴 시간 우려내어 부드럽고 깊은 풍미를 가진 커피입니다.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Iced_Coffee_in_Glass_-_Sunshine_Coffee_-_Laramie_Cafe_%2853838344552%29.jpg/960px-Iced_Coffee_in_Glass_-_Sunshine_Coffee_-_Laramie_Cafe_%2853838344552%29.jpg",
    temperatures: ["ICE"],
    badge: null,
    soldOut: false,
  },
  {
    id: "menu-7",
    name: "에스프레소",
    category: "coffee",
    price: 3500,
    description: "군더더기 없이 진하고 강렬한 커피 본연의 맛을 느낄 수 있습니다.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Espresso_shot.jpg/960px-Espresso_shot.jpg",
    temperatures: ["HOT"],
    badge: null,
    soldOut: false,
  },
  {
    id: "menu-8",
    name: "초콜릿라떼",
    category: "non-coffee",
    price: 5500,
    description: "진한 초콜릿과 부드러운 우유가 만나 달콤함을 더한 음료입니다.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Hot_chocolate.jpg/960px-Hot_chocolate.jpg",
    temperatures: ["HOT", "ICE"],
    badge: null,
    soldOut: false,
  },
  {
    id: "menu-9",
    name: "그린티라떼",
    category: "non-coffee",
    price: 5800,
    description: "고소한 말차와 부드러운 우유가 조화롭게 어우러진 음료입니다.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Matcha_latte_in_tall_glass.jpg/960px-Matcha_latte_in_tall_glass.jpg",
    temperatures: ["HOT", "ICE"],
    badge: null,
    soldOut: false,
  },
  {
    id: "menu-10",
    name: "유자차",
    category: "tea",
    price: 5000,
    description: "새콤달콤한 유자로 만들어 상큼하고 향긋한 전통차입니다.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Korean_yuja_tea.jpg/960px-Korean_yuja_tea.jpg",
    temperatures: ["HOT", "ICE"],
    badge: null,
    soldOut: false,
  },
  {
    id: "menu-11",
    name: "캐모마일티",
    category: "tea",
    price: 4800,
    description: "은은한 꽃향기가 편안함을 더해주는 허브티입니다.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Glass_of_chamomile_tea.jpg/960px-Glass_of_chamomile_tea.jpg",
    temperatures: ["HOT"],
    badge: "NEW",
    soldOut: false,
  },
  {
    id: "menu-12",
    name: "페퍼민트티",
    category: "tea",
    price: 4800,
    description: "상쾌한 민트 향이 가득해 입안을 개운하게 해주는 허브티입니다.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Peppermint-tea_hg.jpg/960px-Peppermint-tea_hg.jpg",
    temperatures: ["HOT", "ICE"],
    badge: null,
    soldOut: false,
  },
  {
    id: "menu-13",
    name: "티라미수",
    category: "dessert",
    price: 6500,
    description: "부드러운 마스카포네 크림과 촉촉한 커피 시트가 어우러진 디저트입니다.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/%D0%9C%D0%B0%D0%BA%D0%B5%D0%B4%D0%BE%D0%BD%D1%81%D0%BA%D0%B8_%D0%B4%D0%B5%D1%81%D0%B5%D1%80%D1%82_%D1%82%D0%B8%D1%80%D0%B0%D0%BC%D0%B8%D1%81%D1%83_%281%29.jpg/960px-%D0%9C%D0%B0%D0%BA%D0%B5%D0%B4%D0%BE%D0%BD%D1%81%D0%BA%D0%B8_%D0%B4%D0%B5%D1%81%D0%B5%D1%80%D1%82_%D1%82%D0%B8%D1%80%D0%B0%D0%BC%D0%B8%D1%81%D1%83_%281%29.jpg",
    temperatures: [],
    badge: "BEST",
    soldOut: false,
  },
  {
    id: "menu-14",
    name: "뉴욕치즈케이크",
    category: "dessert",
    price: 6800,
    description: "진하고 크리미한 정통 뉴욕 스타일의 묵직한 치즈케이크입니다.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/New_York_cheesecake_2.jpg/960px-New_York_cheesecake_2.jpg",
    temperatures: [],
    badge: null,
    soldOut: false,
  },
  {
    id: "menu-15",
    name: "크루아상",
    category: "dessert",
    price: 4200,
    description: "겹겹이 쌓아 구워 바삭한 결이 살아있는 프랑스식 페이스트리입니다.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Two_croissants_on_a_plate_%287326367390%29.jpg/960px-Two_croissants_on_a_plate_%287326367390%29.jpg",
    temperatures: [],
    badge: null,
    soldOut: true,
  },
  {
    id: "menu-16",
    name: "초코쿠키",
    category: "dessert",
    price: 3500,
    description: "진한 초콜릿 청크가 듬뿍 들어간 겉바속촉 수제 쿠키입니다.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Chocolate_chip_cookies_fresh_from_the_oven%2C_July_2024.jpg/960px-Chocolate_chip_cookies_fresh_from_the_oven%2C_July_2024.jpg",
    temperatures: [],
    badge: null,
    soldOut: false,
  },
];
