// ===== 카페 앱 - 메뉴 / 카테고리 데이터 =====

export const CATEGORIES = [
  { id: "coffee", name: "커피" },
  { id: "non-coffee", name: "논커피" },
  { id: "tea", name: "티" },
  { id: "dessert", name: "디저트" },
];

export const TEMPERATURES = [
  { id: "HOT", name: "HOT" },
  { id: "ICE", name: "ICE" },
];

export const ORDER_STATUSES = [
  { id: "received", name: "접수" },
  { id: "preparing", name: "준비중" },
  { id: "done", name: "완료" },
  { id: "canceled", name: "취소" },
];

export const FEEDBACK_CATEGORIES = [
  { id: "complaint", name: "불편사항" },
  { id: "suggestion", name: "건의사항" },
];

// 커피 메뉴 상세 페이지에서 선택하는 원두 종류 (대중적인 산지 위주로 구성)
export const BEAN_ORIGINS = [
  { id: "colombia", name: "콜롬비아", desc: "부드럽고 균형 잡힌 클래식한 맛" },
  { id: "ethiopia", name: "에티오피아", desc: "화사한 꽃향과 산뜻한 산미" },
  { id: "brazil", name: "브라질", desc: "고소한 너티함과 묵직한 바디감" },
];

// 온도 옵션이 있는(=음료) 메뉴에서 선택하는 사이즈
export const SIZE_OPTIONS = [
  { id: "regular", name: "Regular", priceDiff: 0 },
  { id: "large", name: "Large", priceDiff: 500 },
];

// 커피 메뉴에서 선택하는 샷 옵션
export const SHOT_OPTIONS = [
  { id: "normal", name: "기본" },
  { id: "extra", name: "샷 추가" },
  { id: "mild", name: "연하게" },
];

// 온도 옵션이 있는(=음료) 메뉴에서 선택하는 물 양
export const WATER_OPTIONS = [
  { id: "normal", name: "보통" },
  { id: "less", name: "물 적게" },
  { id: "more", name: "물 많이" },
];

// 온도 옵션이 있는(=음료) 메뉴에서 선택하는 얼음 양
export const ICE_OPTIONS = [
  { id: "normal", name: "보통" },
  { id: "less", name: "얼음 적게" },
  { id: "more", name: "얼음 많이" },
];

// 최초 1회 localStorage 시딩에 사용되는 기본 메뉴 데이터
export const INITIAL_MENUS = [
  {
    id: "menu-1",
    name: "아메리카노",
    category: "coffee",
    price: 4500,
    description: "진하게 내린 에스프레소에 물을 더해 깔끔하게 즐기는 기본 커피입니다.",
    image: "menu-1.jpg",
    temperatures: ["HOT", "ICE"],
    badge: "BEST",
    soldOut: false,
    signature: false,
  },
  {
    id: "menu-2",
    name: "카페라떼",
    category: "coffee",
    price: 5000,
    description: "부드러운 스팀 밀크와 에스프레소가 조화를 이루는 커피입니다.",
    image: "menu-2.jpg",
    temperatures: ["HOT", "ICE"],
    badge: "BEST",
    soldOut: false,
    signature: false,
  },
  {
    id: "menu-3",
    name: "바닐라라떼",
    category: "coffee",
    price: 5500,
    description: "달콤한 바닐라 시럽이 더해져 부드럽고 향긋한 라떼입니다.",
    image: "menu-3.jpg",
    temperatures: ["HOT", "ICE"],
    badge: null,
    soldOut: false,
    signature: false,
  },
  {
    id: "menu-4",
    name: "카푸치노",
    category: "coffee",
    price: 5000,
    description: "풍성하고 부드러운 우유 거품이 매력적인 이탈리안 커피입니다.",
    image: "menu-4.jpg",
    temperatures: ["HOT", "ICE"],
    badge: null,
    soldOut: false,
    signature: false,
  },
  {
    id: "menu-5",
    name: "카라멜마키아토",
    category: "coffee",
    price: 5800,
    description: "달콤 쌉싸름한 카라멜과 에스프레소가 층층이 어우러진 커피입니다.",
    image: "menu-5.jpg",
    temperatures: ["HOT", "ICE"],
    badge: null,
    soldOut: false,
    signature: false,
  },
  {
    id: "menu-6",
    name: "콜드브루",
    category: "coffee",
    price: 5200,
    description: "찬물로 긴 시간 우려내어 부드럽고 깊은 풍미를 가진 커피입니다.",
    image: "menu-6.jpg",
    temperatures: ["ICE"],
    badge: null,
    soldOut: false,
    signature: false,
  },
  {
    id: "menu-7",
    name: "에스프레소",
    category: "coffee",
    price: 3500,
    description: "군더더기 없이 진하고 강렬한 커피 본연의 맛을 느낄 수 있습니다.",
    image: "menu-7.jpg",
    temperatures: ["HOT"],
    badge: null,
    soldOut: false,
    signature: false,
  },
  {
    id: "menu-8",
    name: "초콜릿라떼",
    category: "non-coffee",
    price: 5500,
    description: "진한 초콜릿과 부드러운 우유가 만나 달콤함을 더한 음료입니다.",
    image: "menu-8.jpg",
    temperatures: ["HOT", "ICE"],
    badge: null,
    soldOut: false,
    signature: false,
  },
  {
    id: "menu-9",
    name: "그린티라떼",
    category: "non-coffee",
    price: 5800,
    description: "고소한 말차와 부드러운 우유가 조화롭게 어우러진 음료입니다.",
    image: "menu-9.jpg",
    temperatures: ["HOT", "ICE"],
    badge: null,
    soldOut: false,
    signature: false,
  },
  {
    id: "menu-10",
    name: "유자차",
    category: "tea",
    price: 5000,
    description: "새콤달콤한 유자로 만들어 상큼하고 향긋한 전통차입니다.",
    image: "menu-10.jpg",
    temperatures: ["HOT", "ICE"],
    badge: null,
    soldOut: false,
    signature: false,
  },
  {
    id: "menu-11",
    name: "캐모마일티",
    category: "tea",
    price: 4800,
    description: "은은한 꽃향기가 편안함을 더해주는 허브티입니다.",
    image: "menu-11.jpg",
    temperatures: ["HOT"],
    badge: "NEW",
    soldOut: false,
    signature: false,
  },
  {
    id: "menu-12",
    name: "페퍼민트티",
    category: "tea",
    price: 4800,
    description: "상쾌한 민트 향이 가득해 입안을 개운하게 해주는 허브티입니다.",
    image: "menu-12.jpg",
    temperatures: ["HOT", "ICE"],
    badge: null,
    soldOut: false,
    signature: false,
  },
  {
    id: "menu-13",
    name: "티라미수",
    category: "dessert",
    price: 6500,
    description: "부드러운 마스카포네 크림과 촉촉한 커피 시트가 어우러진 디저트입니다.",
    image: "menu-13.jpg",
    temperatures: [],
    badge: "BEST",
    soldOut: false,
    signature: true,
  },
  {
    id: "menu-14",
    name: "뉴욕치즈케이크",
    category: "dessert",
    price: 6800,
    description: "진하고 크리미한 정통 뉴욕 스타일의 묵직한 치즈케이크입니다.",
    image: "menu-14.jpg",
    temperatures: [],
    badge: null,
    soldOut: false,
    signature: false,
  },
  {
    id: "menu-15",
    name: "크루아상",
    category: "dessert",
    price: 4200,
    description: "겹겹이 쌓아 구워 바삭한 결이 살아있는 프랑스식 페이스트리입니다.",
    image: "menu-15.jpg",
    temperatures: [],
    badge: null,
    soldOut: true,
    signature: false,
  },
  {
    id: "menu-16",
    name: "초코쿠키",
    category: "dessert",
    price: 3500,
    description: "진한 초콜릿 청크가 듬뿍 들어간 겉바속촉 수제 쿠키입니다.",
    image: "menu-16.jpg",
    temperatures: [],
    badge: null,
    soldOut: false,
    signature: false,
  },
  {
    id: "menu-17",
    name: "플랫화이트",
    category: "coffee",
    price: 5300,
    description: "진한 에스프레소에 얇은 밀크 폼을 더해 부드럽고 진한 풍미가 살아있는 커피입니다.",
    image: "menu-17.jpg",
    temperatures: ["HOT", "ICE"],
    badge: null,
    soldOut: false,
    signature: true,
  },
  {
    id: "menu-18",
    name: "아인슈페너",
    category: "coffee",
    price: 6000,
    description: "진한 커피 위에 부드러운 크림을 듬뿍 올려 달콤 쌉싸름하게 즐기는 비엔나 커피입니다.",
    image: "menu-18.jpg",
    temperatures: ["HOT", "ICE"],
    badge: "NEW",
    soldOut: false,
    signature: true,
  },
  {
    id: "menu-19",
    name: "헤이즐넛라떼",
    category: "coffee",
    price: 5600,
    description: "고소한 헤이즐넛 시럽과 부드러운 우유가 에스프레소와 어우러진 향긋한 라떼입니다.",
    image: "menu-19.jpg",
    temperatures: ["HOT", "ICE"],
    badge: "NEW",
    soldOut: false,
    signature: true,
  },
  {
    id: "menu-20",
    name: "흑당버블라떼",
    category: "non-coffee",
    price: 5800,
    description: "진한 흑당 시럽과 쫀득한 타피오카 펄이 들어간 달콤한 밀크 음료입니다.",
    image: "menu-20.jpg",
    temperatures: ["ICE"],
    badge: "BEST",
    soldOut: false,
    signature: false,
  },
  {
    id: "menu-21",
    name: "얼그레이티",
    category: "tea",
    price: 4800,
    description: "은은한 베르가못 향이 매력적인 향긋하고 우아한 홍차입니다.",
    image: "menu-21.jpg",
    temperatures: ["HOT", "ICE"],
    badge: null,
    soldOut: false,
    signature: false,
  },
  {
    id: "menu-22",
    name: "마카롱",
    category: "dessert",
    price: 3800,
    description: "쫀득한 코크와 부드러운 필링이 조화로운 색색의 프랑스식 디저트입니다.",
    image: "menu-22.jpg",
    temperatures: [],
    badge: null,
    soldOut: false,
    signature: false,
  },
];
